import type { TValueOf } from '@blog/config/utils';

export const DEPROVISIONING_STEP = {
  REMOVE_DOMAIN: 'REMOVE_DOMAIN',
  ARCHIVE_SANITY_PROJECT: 'ARCHIVE_SANITY_PROJECT',
  REVOKE_SANITY_TOKENS: 'REVOKE_SANITY_TOKENS',
  CLEAR_ARTIFACTS: 'CLEAR_ARTIFACTS',
  ARCHIVE_TENANT: 'ARCHIVE_TENANT',
  INVALIDATE_TENANT_CACHE: 'INVALIDATE_TENANT_CACHE',
} as const;

export type TDeprovisioningStep = TValueOf<typeof DEPROVISIONING_STEP>;

// Every step `scripts/deprovision-tenant/run.ts`'s `STEPS` array runs, in
// the exact order it runs them.
export const CORE_DEPROVISIONING_STEPS = [
  DEPROVISIONING_STEP.REMOVE_DOMAIN,
  DEPROVISIONING_STEP.ARCHIVE_SANITY_PROJECT,
  DEPROVISIONING_STEP.REVOKE_SANITY_TOKENS,
  DEPROVISIONING_STEP.CLEAR_ARTIFACTS,
  DEPROVISIONING_STEP.ARCHIVE_TENANT,
  DEPROVISIONING_STEP.INVALIDATE_TENANT_CACHE,
] as const satisfies readonly TDeprovisioningStep[];
