import {
  CORE_DEPROVISIONING_STEPS,
  DEPROVISIONING_STEP,
} from './tenant-deprovisioning';

describe('CORE_DEPROVISIONING_STEPS', () => {
  it("matches run.ts's step execution order", () => {
    expect(CORE_DEPROVISIONING_STEPS).toEqual([
      DEPROVISIONING_STEP.REMOVE_DOMAIN,
      DEPROVISIONING_STEP.ARCHIVE_SANITY_PROJECT,
      DEPROVISIONING_STEP.REVOKE_SANITY_TOKENS,
      DEPROVISIONING_STEP.CLEAR_ARTIFACTS,
      DEPROVISIONING_STEP.ARCHIVE_TENANT,
      DEPROVISIONING_STEP.INVALIDATE_TENANT_CACHE,
    ]);
  });
});
