/**
 * Every `site-messages.en.json` key deliberately left out of `VOICE_FIELDS`,
 * grouped by why: accessibility-only text, generic toast/operation feedback,
 * counters carrying ICU plural syntax, metadata with no visible counterpart,
 * archive/breadcrumb labels derived from Studio content, a taxonomy label
 * tied to a Sanity-modelled enum, fixed operational newsletter copy, and
 * fixed sign-in interface mechanics. The coverage test fails if a catalog
 * key is on neither this list nor `VOICE_FIELDS`, so a new string can't be
 * added without deciding which.
 */
export const VOICE_FIXED_KEYS = [
  'breadcrumbs.ariaLabel',
  'localeErrorPage.announcement',
  'postShare.shareAriaLabel',
  'postShare.panelAriaLabel',
  'siteNavigation.toggleMenu',
  'brandLockupLink.ariaLabel',
  'socialLinks.linkAriaLabel',
  'topicChipList.ariaLabel',
  'blogListPage.paginationAriaLabel',
  'blogPostPage.depthToggle.ariaLabel',
  'blogPostPage.backToTop.ariaLabel',
  'topicPage.paginationAriaLabel',
  'tagPage.paginationAriaLabel',
  'rss.feedLinkLabel',
  'authMenu.panelAriaLabel',
  'authMenu.emailAriaLabel',
  'authMenu.accountMenuAriaLabel',
  'authMenu.loadingAccountStatus',
  'toastProvider.viewportAriaLabel',
  'toastProvider.dismissLabel',
  'bookmarkButton.saveAriaLabel',
  'bookmarkButton.removeAriaLabel',
  'accountPage.privacy.deleteConfirmAriaLabel',
  'accountPage.identity.displayNameAriaLabel',
  'taxonomyListModule.topics.latestPostsLabel',
  'taxonomyListModule.tags.latestPostsLabel',
  'carousel.previousAriaLabel',
  'carousel.nextAriaLabel',
  'carousel.regionLabel',
  'hero.socialLinksAriaLabel',

  'breadcrumbs.home',
  'breadcrumbs.topics',
  'breadcrumbs.tags',
  'breadcrumbs.blog',

  'blogPostPage.asideKind.WHY_NOT',
  'blogPostPage.asideKind.DIGRESSION',
  'blogPostPage.asideKind.CONTEXT',

  'bookmarkButton.error',
  'bookmarkButton.toastSavedMessage',
  'bookmarkButton.toastRemovedMessage',
  'bookmarkButton.toastRevertedMessage',
  'bookmarkButton.toastUndoLabel',
  'bookmarkButton.toastRetryLabel',
  'accountPage.privacy.deleteToastLoadingMessage',
  'accountPage.privacy.deleteToastSuccessMessage',
  'accountPage.privacy.deleteError',
  'accountPage.newsletter.unsubscribeToastLoadingMessage',
  'accountPage.newsletter.unsubscribeToastSuccessMessage',
  'accountPage.newsletter.unsubscribeError',
  'accountPage.newsletter.resendToastLoadingMessage',
  'accountPage.newsletter.resendToastSuccessMessage',
  'accountPage.newsletter.resendError',
  'accountPage.identity.unlinkToastLoadingMessage',
  'accountPage.identity.unlinkToastSuccessMessage',
  'accountPage.identity.unlinkError',
  'accountPage.identity.unlinkLastMethodError',
  'accountPage.identity.saveToastLoadingMessage',
  'accountPage.identity.saveToastSuccessMessage',
  'accountPage.identity.saveError',

  'pagination.pageSuffix',
  'taxonomyListModule.topics.postsCount',
  'taxonomyListModule.tags.postsCount',
  'toastProvider.mergeCountSuffix',
  'bookmarksPage.hint',

  'accountPage.metaDescription',
  'bookmarksPage.metaDescription',
  'rss.fallbackTitle',

  'newsletterForm.submitLabel',
  'newsletterForm.emailAriaLabel',
  'newsletterForm.placeholder',
  'newsletterForm.successMessage',
  'newsletterForm.errorInvalid',
  'newsletterForm.errorAlreadySubscribed',
  'newsletterForm.errorServer',
  'newsletterConfirm.confirmedTitle',
  'newsletterConfirm.confirmedMessage',
  'newsletterConfirm.invalidTitle',
  'newsletterConfirm.invalidMessage',
  'newsletterConfirm.errorTitle',
  'newsletterConfirm.errorMessage',
  'newsletterConfirm.returnHome',
  'newsletterUnsubscribe.confirmTitle',
  'newsletterUnsubscribe.confirmMessage',
  'newsletterUnsubscribe.confirmButtonLabel',
  'newsletterUnsubscribe.successTitle',
  'newsletterUnsubscribe.successMessage',
  'newsletterUnsubscribe.invalidTitle',
  'newsletterUnsubscribe.invalidMessage',
  'newsletterUnsubscribe.returnHome',

  'authMenu.signIn',
  'authMenu.signInHeading',
  'authMenu.accountHeading',
  'authMenu.chooseProviderPrompt',
  'authMenu.continueWithGithub',
  'authMenu.continueWithGoogle',
  'authMenu.continueWithEmail',
  'authMenu.redirectHint',
  'authMenu.emailPlaceholder',
  'authMenu.sendLink',
  'authMenu.sending',
  'authMenu.checkYourInbox',
  'authMenu.emailError',
  'authMenu.oauthError',
  'authMenu.signOut',
  'authMenu.myBookmarks',
  'authMenu.accountSettings',
] as const;
