import { VOICE_FIELD_KIND } from './voice-field-kind';
import { VOICE_SURFACE } from './voice-surface';

/**
 * Every tenant-editable string on the site: `path` locates it in
 * `site-messages.en.json`, `id` is the flat storage key persisted on
 * `site_config.voiceOverrides`. A key absent from this array and from
 * `VOICE_FIXED_KEYS` is a defect the coverage test catches.
 */
export const VOICE_FIELDS = [
  {
    id: 'paginationPrevious',
    path: 'pagination.previous',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: [],
    max: 100,
  },
  {
    id: 'paginationNext',
    path: 'pagination.next',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: [],
    max: 100,
  },
  {
    id: 'blogListEmpty',
    path: 'blogListPage.empty',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: [],
    max: 300,
  },
  {
    id: 'topicEmpty',
    path: 'topicPage.empty',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: ['name'],
    max: 300,
  },
  {
    id: 'tagEmpty',
    path: 'tagPage.empty',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: ['name'],
    max: 300,
  },
  {
    id: 'topicsEmpty',
    path: 'topicsPage.empty',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: [],
    max: 300,
  },
  {
    id: 'tagsEmpty',
    path: 'tagsPage.empty',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ARCHIVE,
    placeholders: [],
    max: 300,
  },
  {
    id: 'topicChipListAll',
    path: 'topicChipList.all',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.NAVIGATION,
    placeholders: [],
    max: 40,
  },
  {
    id: 'blogPostDepthToggleSkim',
    path: 'blogPostPage.depthToggle.skim',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.POST,
    placeholders: [],
    max: 40,
  },
  {
    id: 'blogPostDepthToggleRead',
    path: 'blogPostPage.depthToggle.read',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.POST,
    placeholders: [],
    max: 40,
  },
  {
    id: 'blogPostDepthToggleDeep',
    path: 'blogPostPage.depthToggle.deep',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.POST,
    placeholders: [],
    max: 40,
  },
  {
    id: 'blogPostSkimPanelLabel',
    path: 'blogPostPage.skimPanel.label',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.POST,
    placeholders: [],
    max: 100,
  },
  {
    id: 'blogPostSkimPanelReadFullArticle',
    path: 'blogPostPage.skimPanel.readFullArticle',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.POST,
    placeholders: [],
    max: 100,
  },
  {
    id: 'postContentsRailLabel',
    path: 'postContentsRail.label',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.POST,
    placeholders: [],
    max: 40,
  },
  {
    id: 'postShareCopyLink',
    path: 'postShare.copyLink',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SHARING,
    placeholders: [],
    max: 40,
  },
  {
    id: 'postShareCopied',
    path: 'postShare.copied',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SHARING,
    placeholders: [],
    max: 40,
  },
  {
    id: 'postShareLinkCopied',
    path: 'postShare.linkCopied',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SHARING,
    placeholders: [],
    max: 100,
  },
  {
    id: 'notFoundEyebrow',
    path: 'notFound.eyebrow',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.NOT_FOUND,
    placeholders: [],
    max: 40,
  },
  {
    id: 'notFoundHeading',
    path: 'notFound.heading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.NOT_FOUND,
    placeholders: [],
    max: 100,
  },
  {
    id: 'notFoundSupportingText',
    path: 'notFound.supportingText',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.NOT_FOUND,
    placeholders: [],
    max: 300,
  },
  {
    id: 'notFoundReturnHome',
    path: 'notFound.returnHome',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.NOT_FOUND,
    placeholders: [],
    max: 100,
  },
  {
    id: 'localeErrorTitle',
    path: 'localeErrorPage.title',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ERROR,
    placeholders: [],
    max: 100,
  },
  {
    id: 'localeErrorDescription',
    path: 'localeErrorPage.description',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ERROR,
    placeholders: [],
    max: 300,
  },
  {
    id: 'localeErrorRetry',
    path: 'localeErrorPage.retry',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ERROR,
    placeholders: [],
    max: 100,
  },
  {
    id: 'localeErrorGoHome',
    path: 'localeErrorPage.goHome',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ERROR,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuSignIn',
    path: 'authMenu.signIn',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 40,
  },
  {
    id: 'authMenuSignInHeading',
    path: 'authMenu.signInHeading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuAccountHeading',
    path: 'authMenu.accountHeading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuChooseProviderPrompt',
    path: 'authMenu.chooseProviderPrompt',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuContinueWithGithub',
    path: 'authMenu.continueWithGithub',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuContinueWithGoogle',
    path: 'authMenu.continueWithGoogle',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuContinueWithEmail',
    path: 'authMenu.continueWithEmail',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuRedirectHint',
    path: 'authMenu.redirectHint',
    kind: VOICE_FIELD_KIND.MULTILINE,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 300,
  },
  {
    id: 'authMenuEmailPlaceholder',
    path: 'authMenu.emailPlaceholder',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuSendLink',
    path: 'authMenu.sendLink',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuSending',
    path: 'authMenu.sending',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuCheckYourInbox',
    path: 'authMenu.checkYourInbox',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuEmailError',
    path: 'authMenu.emailError',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuOauthError',
    path: 'authMenu.oauthError',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuSignOut',
    path: 'authMenu.signOut',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuMyBookmarks',
    path: 'authMenu.myBookmarks',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'authMenuAccountSettings',
    path: 'authMenu.accountSettings',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.SIGN_IN,
    placeholders: [],
    max: 100,
  },
  {
    id: 'bookmarkButtonSave',
    path: 'bookmarkButton.save',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.BOOKMARKS,
    placeholders: [],
    max: 40,
  },
  {
    id: 'bookmarkButtonSaved',
    path: 'bookmarkButton.saved',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.BOOKMARKS,
    placeholders: [],
    max: 40,
  },
  {
    id: 'bookmarksTitle',
    path: 'bookmarksPage.title',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.BOOKMARKS,
    placeholders: [],
    max: 100,
  },
  {
    id: 'bookmarksListHeading',
    path: 'bookmarksPage.listHeading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.BOOKMARKS,
    placeholders: [],
    max: 100,
  },
  {
    id: 'bookmarksEmpty',
    path: 'bookmarksPage.empty',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.BOOKMARKS,
    placeholders: [],
    max: 300,
  },
  {
    id: 'accountTitle',
    path: 'accountPage.title',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountPrivacyHeading',
    path: 'accountPage.privacy.heading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountPrivacyExportLabel',
    path: 'accountPage.privacy.exportLabel',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountPrivacyExportDescription',
    path: 'accountPage.privacy.exportDescription',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 300,
  },
  {
    id: 'accountPrivacyExportButton',
    path: 'accountPage.privacy.exportButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountPrivacyDeleteLabel',
    path: 'accountPage.privacy.deleteLabel',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountPrivacyDeleteDescription',
    path: 'accountPage.privacy.deleteDescription',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 300,
  },
  {
    id: 'accountPrivacyDeleteConfirmPlaceholder',
    path: 'accountPage.privacy.deleteConfirmPlaceholder',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: ['handle'],
    max: 100,
  },
  {
    id: 'accountPrivacyDeleteButton',
    path: 'accountPage.privacy.deleteButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountNewsletterHeading',
    path: 'accountPage.newsletter.heading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountNewsletterLabel',
    path: 'accountPage.newsletter.label',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountNewsletterActiveBadge',
    path: 'accountPage.newsletter.activeBadge',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountNewsletterActiveDescriptionPrefix',
    path: 'accountPage.newsletter.activeDescriptionPrefix',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 150,
  },
  {
    id: 'accountNewsletterActiveDescriptionSuffix',
    path: 'accountPage.newsletter.activeDescriptionSuffix',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 150,
  },
  {
    id: 'accountNewsletterUnsubscribeButton',
    path: 'accountPage.newsletter.unsubscribeButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountNewsletterPendingBadge',
    path: 'accountPage.newsletter.pendingBadge',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountNewsletterPendingDescription',
    path: 'accountPage.newsletter.pendingDescription',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 300,
  },
  {
    id: 'accountNewsletterResendButton',
    path: 'accountPage.newsletter.resendButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountIdentityHeading',
    path: 'accountPage.identity.heading',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountIdentityGithubLabel',
    path: 'accountPage.identity.githubLabel',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountIdentityGoogleLabel',
    path: 'accountPage.identity.googleLabel',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountIdentityEmailLinkLabel',
    path: 'accountPage.identity.emailLinkLabel',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountIdentityLinkedStatus',
    path: 'accountPage.identity.linkedStatus',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountIdentityLinkButton',
    path: 'accountPage.identity.linkButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountIdentityUnlinkButton',
    path: 'accountPage.identity.unlinkButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
  {
    id: 'accountIdentityLastMethodNotice',
    path: 'accountPage.identity.lastMethodNotice',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountIdentityDisplayNameLabel',
    path: 'accountPage.identity.displayNameLabel',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 100,
  },
  {
    id: 'accountIdentityDisplayNameDescription',
    path: 'accountPage.identity.displayNameDescription',
    kind: VOICE_FIELD_KIND.RICH,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 300,
  },
  {
    id: 'accountIdentitySaveButton',
    path: 'accountPage.identity.saveButton',
    kind: VOICE_FIELD_KIND.TEXT,
    surface: VOICE_SURFACE.ACCOUNT,
    placeholders: [],
    max: 40,
  },
] as const;

export type TVoiceFieldId = (typeof VOICE_FIELDS)[number]['id'];
