// Generated by the cms package via `sanity typegen generate`.
// Run `pnpm typegen` after any schema change.
export * from './sanity.types';

// Hand-written shared shapes can also live here:
// export interface NavLink { label: string; href: string }
