import { pgTable, text, timestamp, unique, uuid } from 'drizzle-orm/pg-core';

import { tenants } from './tenants';

// Newsletter double opt-in. A subscriber is a standalone email
// subscription, not scoped to a signed-in `users` row — a signed-out
// reader can subscribe — so unlike `bookmarks.ts` there is no `userId` FK
// here at all, real or logical.
//
// One row per (tenantId, email) pair, ever, and `status` moves `pending` →
// `active` in place on that same row (see
// `queries/subscribers/confirm-subscriber`) rather than a new row being
// inserted at confirmation time. `email` is no longer globally unique on its
// own: the same reader can subscribe to two different tenants' newsletters
// with the same address, so uniqueness is scoped to the pair instead.
export const SUBSCRIBER_STATUS = ['pending', 'active'] as const;
export type TSubscriberStatus = (typeof SUBSCRIBER_STATUS)[number];

export const subscribers = pgTable(
  'subscribers',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    tenantId: uuid('tenant_id')
      .notNull()
      .references(() => tenants.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    status: text('status', { enum: SUBSCRIBER_STATUS })
      .notNull()
      .default('pending'),
    // The token embedded in the confirmation-email link
    // (`/newsletter/confirm?token=...`). Generated the same way `users.id`
    // is (auth.ts) — `crypto.randomUUID()` is unguessable enough for a
    // confirm-by-click link, and generating it here (rather
    // than in `web`, the way Auth.js's own `verificationTokens` token is
    // generated by the library that owns that table, not this schema) keeps
    // token issuance a `db`-layer concern the caller can't get wrong. It
    // stays globally unique (not scoped to tenantId) — a random UUID
    // already uniquely identifies one row regardless of tenant, and the
    // confirm link only ever carries the token, not a tenant identifier.
    confirmationToken: text('confirmation_token')
      .notNull()
      .unique()
      .$defaultFn(() => crypto.randomUUID()),
    subscribedAt: timestamp('subscribed_at', { mode: 'date' })
      .notNull()
      .defaultNow(),
    // Set when `status` flips to `active`. Nullable/`undefined` (never a
    // sentinel date) while still `pending` — see
    // `queries/subscribers/confirm-subscriber`'s view-model mapping.
    confirmedAt: timestamp('confirmed_at', { mode: 'date' }),
  },
  (subscriber) => [unique().on(subscriber.tenantId, subscriber.email)],
);

export type TSubscriber = typeof subscribers.$inferSelect;
