import type { TValueOf } from '@blog/config/utils';

export const ICONS = {
  SUN: 'SUN',
  MOON: 'MOON',
  HOUSE: 'HOUSE',
  SHARE: 'SHARE',
  COPY: 'COPY',
  CHECK: 'CHECK',
  CHECK_SHEET: 'CHECK_SHEET',
  EXTERNAL_LINK: 'EXTERNAL_LINK',
  MENU: 'MENU',
  MENU_ROWS: 'MENU_ROWS',
  CLOSE: 'CLOSE',
  X: 'X',
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN',
  FACEBOOK: 'FACEBOOK',
  RSS: 'RSS',
  ARROW_UP: 'ARROW_UP',
  GOOGLE: 'GOOGLE',
  BOOKMARK: 'BOOKMARK',
  SPINNER: 'SPINNER',
  WARNING: 'WARNING',
  INFO: 'INFO',
  SETTINGS: 'SETTINGS',
  POWER: 'POWER',
  MAIL: 'MAIL',
  CHEVRON_RIGHT: 'CHEVRON_RIGHT',
  ARROW: 'ARROW',
} as const;

export type TIconName = TValueOf<typeof ICONS>;
