import { ICONS, type TIconName } from './icon';

export const LINK_TYPE = {
  INTERNAL: 'INTERNAL',
  EXTERNAL: 'EXTERNAL',
} as const;

export type TLinkType = (typeof LINK_TYPE)[keyof typeof LINK_TYPE];

export const SOCIAL_PLATFORMS = {
  X: 'X',
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN',
  YOUTUBE: 'YOUTUBE',
  INSTAGRAM: 'INSTAGRAM',
  MASTODON: 'MASTODON',
  BLUESKY: 'BLUESKY',
  FACEBOOK: 'FACEBOOK',
  THREADS: 'THREADS',
  RSS: 'RSS',
} as const;

export type TSocialPlatform =
  (typeof SOCIAL_PLATFORMS)[keyof typeof SOCIAL_PLATFORMS];

export const SOCIAL_PLATFORM_LABEL: Record<TSocialPlatform, string> = {
  [SOCIAL_PLATFORMS.X]: 'X',
  [SOCIAL_PLATFORMS.GITHUB]: 'GitHub',
  [SOCIAL_PLATFORMS.LINKEDIN]: 'LinkedIn',
  [SOCIAL_PLATFORMS.YOUTUBE]: 'YouTube',
  [SOCIAL_PLATFORMS.INSTAGRAM]: 'Instagram',
  [SOCIAL_PLATFORMS.MASTODON]: 'Mastodon',
  [SOCIAL_PLATFORMS.BLUESKY]: 'Bluesky',
  [SOCIAL_PLATFORMS.FACEBOOK]: 'Facebook',
  [SOCIAL_PLATFORMS.THREADS]: 'Threads',
  [SOCIAL_PLATFORMS.RSS]: 'RSS',
};

export const SOCIAL_PLATFORM_ICON: Record<TSocialPlatform, TIconName> = {
  [SOCIAL_PLATFORMS.X]: ICONS.X,
  [SOCIAL_PLATFORMS.GITHUB]: ICONS.GITHUB,
  [SOCIAL_PLATFORMS.LINKEDIN]: ICONS.LINKEDIN,
  [SOCIAL_PLATFORMS.YOUTUBE]: ICONS.YOUTUBE,
  [SOCIAL_PLATFORMS.INSTAGRAM]: ICONS.INSTAGRAM,
  [SOCIAL_PLATFORMS.MASTODON]: ICONS.MASTODON,
  [SOCIAL_PLATFORMS.BLUESKY]: ICONS.BLUESKY,
  [SOCIAL_PLATFORMS.FACEBOOK]: ICONS.FACEBOOK,
  [SOCIAL_PLATFORMS.THREADS]: ICONS.THREADS,
  [SOCIAL_PLATFORMS.RSS]: ICONS.RSS,
};
