import { defineField, defineType } from 'sanity';

export const skimSchema = defineType({
  name: 'skim',
  title: 'Skim',
  type: 'object',
  description:
    '30-second-skim content, generated by the reading-depth pipeline.',
  options: { collapsible: true, collapsed: true },
  fields: [
    defineField({
      name: 'takeaways',
      title: 'Takeaways',
      type: 'array',
      description: '3–7 short takeaways, each under 160 characters.',
      of: [{ type: 'string', validation: (rule) => rule.max(160) }],
      validation: (rule) => rule.min(3).max(7),
    }),
    defineField({
      name: 'generatedAt',
      title: 'Generated At',
      type: 'datetime',
      description: 'Set by the reading-depth pipeline.',
      readOnly: true,
    }),
    defineField({
      name: 'model',
      title: 'Model',
      type: 'string',
      description: 'Set by the reading-depth pipeline.',
      readOnly: true,
    }),
  ],
  preview: {
    select: { takeaways: 'takeaways' },
    prepare({ takeaways }: { takeaways?: string[] }) {
      return {
        title: 'Skim',
        subtitle: takeaways?.length
          ? `${takeaways.length} takeaway${takeaways.length === 1 ? '' : 's'}`
          : 'No takeaways yet',
      };
    },
  },
});
